# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    #    param_fetcher_listener:  true
    #    allowed_methods_listener:  true
    routing_loader:
        include_format: true
        default_format: json
    view:
        view_response_listener: true
    #    exception:
    #        codes:
    #            App\Exception\MyException: 403
    #        messages:
    #            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/, priorities: [ 'html', '*/*' ], fallback_format: html, prefer_extension: true }
            - { path: ^/api, priorities: [ 'json' ], fallback_format: 'json' }
